# Generated by Django 5.0 on 2024-03-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Electronic', 'electronic'), ('Fashion', 'Fashion'), ('Grocery', 'Grocery'), ('Home & Furniture', 'Home & furniture'), ('Mobiles', 'mobiles'), ('Appliances', 'Appliance')], max_length=250),
        ),
    ]
