# Generated by Django 5.0 on 2024-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_product_cata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cata_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
