# Generated by Django 5.0.2 on 2024-04-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0012_products_saleprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='saleprice',
            field=models.CharField(max_length=100),
        ),
    ]
