# Generated by Django 5.0.2 on 2024-04-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0015_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
